"use client";

import { useState } from "react";
import { useMutation, useQuery } from "convex/react";
import { ArrowUpRight, Bug, Check, CirclePlus, Copy, Lightbulb, Loader2, MessageSquare, Settings2, X } from "lucide-react";
import { api } from "@/convex/_generated/api";
import type { Id } from "@/convex/_generated/dataModel";
import type { FunctionReturnType } from "convex/server";
import { useWorkspace } from "./workspace-context";
import { Dialog } from "./dialog";
import { ContentSkeleton } from "./content-skeleton";

type Portal = FunctionReturnType<typeof api.feedback.portals>[number];
type Entry = FunctionReturnType<typeof api.feedback.list>[number];

export function FeedbackView({ sessionToken, onOpenTask }: { sessionToken: string; onOpenTask: (projectId: Id<"projects">, taskId: Id<"tasks">) => void }) {
  const workspace = useWorkspace(); const scope = { sessionToken, teamId: workspace._id };
  const projects = useQuery(api.projects.listForUser, scope); const portals = useQuery(api.feedback.portals, scope);
  const [selectedProject, setProject] = useState(""); const [filter, setFilter] = useState("open"); const [config, setConfig] = useState(false); const [entry, setEntry] = useState<Entry | null>(null); const [notice, setNotice] = useState("");
  const project = projects?.find(p => p._id === selectedProject) || projects?.[0];
  const portal = portals?.find(p => p.projectId === project?._id);
  const rows = useQuery(api.feedback.list, portal ? { ...scope, portalId: portal._id } : "skip");
  const dismiss = useMutation(api.feedback.dismiss);
  const admin = ["owner", "admin"].includes(workspace.role);
  const visible = rows?.filter(row => filter === "all" || (filter === "completed" ? row.status === "completed" : row.status === "new" || row.status === "planned"));
  return <section className="feature-page" aria-label="Feedback"><div className="feature-toolbar"><select aria-label="Feedback project" value={project?._id || ""} onChange={e => setProject(e.target.value)}>{projects?.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}</select><div className="segmented-control">{["open", "completed", "all"].map(value => <button key={value} className={value === filter ? "active" : ""} aria-pressed={value === filter} onClick={() => setFilter(value)}>{value[0].toUpperCase() + value.slice(1)}</button>)}</div><div className="feature-toolbar-spacer" />{portal?.enabled && <><button className="icon-button" aria-label="Copy feedback link" title="Copy feedback link" onClick={async () => { try { await navigator.clipboard.writeText(`${window.location.origin}/feedback/${portal.slug}`); setNotice("Feedback link copied"); } catch { setNotice("Could not copy link"); } }}><Copy size={15} /></button><a className="icon-button" title="Open public feedback form" aria-label="Open public feedback form" target="_blank" rel="noreferrer" href={`/feedback/${portal.slug}`}><ArrowUpRight size={16} /></a></>}{admin && <button className="icon-button" disabled={!project} title="Feedback settings" aria-label="Feedback settings" onClick={() => setConfig(true)}><Settings2 size={16} /></button>}</div>{notice && <p className="notice" role="status">{notice}</p>}
    {!projects || !portals ? <ContentSkeleton rows={5} /> : !portal ? <div className="feature-empty"><MessageSquare size={28} /><strong>Feedback is private until you enable a form</strong>{admin && project && <button className="ghost-button compact" onClick={() => setConfig(true)}>Set up feedback</button>}</div> : rows === undefined ? <ContentSkeleton rows={5} /> : !visible?.length ? <div className="feature-empty"><MessageSquare size={28} /><strong>No feedback here yet</strong></div> : <div className="feedback-list">{visible.map(row => <article key={row._id} className="feedback-entry"><header>{row.kind === "bug" ? <Bug size={17} /> : <Lightbulb size={17} />}<strong>{row.title}</strong><span className="feature-status">{row.status}</span></header><p>{row.body}</p><footer><time>{new Date(row.createdAt).toLocaleDateString()}</time><div className="feature-toolbar-spacer" />{row.taskId ? <button className="ghost-button compact" onClick={() => onOpenTask(portal.projectId, row.taskId!)}><ArrowUpRight size={14} />Open issue</button> : workspace.role !== "viewer" && <button className="ghost-button compact" onClick={() => setEntry(row)}><CirclePlus size={14} />Create issue</button>}{workspace.role !== "viewer" && <button className="icon-button" title={row.status === "dismissed" ? "Restore feedback" : "Dismiss feedback"} aria-label={row.status === "dismissed" ? "Restore feedback" : "Dismiss feedback"} onClick={async () => { try { await dismiss({ ...scope, entryId: row._id, dismissed: row.status !== "dismissed" }); } catch (error) { setNotice(error instanceof Error ? error.message : "Could not update"); } }}>{row.status === "dismissed" ? <Check size={14} /> : <X size={14} />}</button>}</footer></article>)}</div>}
    {config && project && <PortalSettings sessionToken={sessionToken} projectId={project._id} projectName={project.name} portal={portal} onClose={() => setConfig(false)} />}
    {entry && portal && <ConvertFeedback sessionToken={sessionToken} projectId={portal.projectId} entry={entry} onClose={() => setEntry(null)} onCreated={taskId => { setEntry(null); onOpenTask(portal.projectId, taskId); }} />}
  </section>;
}

function PortalSettings({ sessionToken, projectId, projectName, portal, onClose }: { sessionToken: string; projectId: Id<"projects">; projectName: string; portal?: Portal; onClose: () => void }) {
  const workspace = useWorkspace(); const save = useMutation(api.feedback.configure);
  const [title, setTitle] = useState(portal?.title || projectName); const [description, setDescription] = useState(portal?.description || ""); const [enabled, setEnabled] = useState(portal?.enabled || false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  return <Dialog title="Feedback settings" onClose={onClose}><form className="feature-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { await save({ sessionToken, teamId: workspace._id, projectId, title, description, enabled }); onClose(); } catch (error) { setError(error instanceof Error ? error.message : "Could not save"); } finally { setBusy(false); } }}><label>Public title<input value={title} required maxLength={120} onChange={e => setTitle(e.target.value)} /></label><label>Public description<textarea value={description} maxLength={3000} rows={4} onChange={e => setDescription(e.target.value)} /></label><label className="feature-checkbox"><input type="checkbox" checked={enabled} onChange={e => setEnabled(e.target.checked)} />Enable public feedback form</label><p className="muted">Enabling this publishes the title and description above. Workspace content, issues and submitted feedback stay private.</p>{error && <p className="notice danger" role="alert">{error}</p>}<button className="primary-button compact" disabled={busy}>{busy ? <Loader2 className="spin" size={15} /> : <Check size={15} />}Save settings</button></form></Dialog>;
}

function ConvertFeedback({ sessionToken, projectId, entry, onClose, onCreated }: { sessionToken: string; projectId: Id<"projects">; entry: Entry; onClose: () => void; onCreated: (id: Id<"tasks">) => void }) {
  const workspace = useWorkspace(); const convert = useMutation(api.feedback.convert);
  const board = useQuery(api.tasks.board, { sessionToken, projectId }); const members = useQuery(api.workspaces.members, { sessionToken, teamId: workspace._id });
  const [column, setColumn] = useState(""); const [assignee, setAssignee] = useState(""); const [dueDate, setDueDate] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const columns = board?.columns.filter(c => !c.isDone && !/^done$/i.test(c.title)) || [];
  return <Dialog title="Create issue from feedback" onClose={onClose}><form className="feature-form" onSubmit={async e => { e.preventDefault(); setBusy(true); try { onCreated(await convert({ sessionToken, teamId: workspace._id, entryId: entry._id, columnId: (column || columns[0]?._id) as Id<"columns">, assignedToEmail: assignee, dueDate })); } catch (error) { setError(error instanceof Error ? error.message : "Could not create issue"); } finally { setBusy(false); } }}><strong>{entry.title}</strong><label>Column<select required value={column || columns[0]?._id || ""} onChange={e => setColumn(e.target.value)}>{columns.map(c => <option key={c._id} value={c._id}>{c.title}</option>)}</select></label><label>Assigned to<select value={assignee} required onChange={e => setAssignee(e.target.value)}><option value="">Choose a member</option>{members?.map(m => <option key={m._id} value={m.email}>{m.username || m.name}</option>)}</select></label><label>Due date<input type="date" required value={dueDate} onChange={e => setDueDate(e.target.value)} /></label>{error && <p className="notice danger" role="alert">{error}</p>}<button className="primary-button compact" disabled={busy || !columns.length}>{busy ? <Loader2 className="spin" size={15} /> : <CirclePlus size={15} />}Create issue</button></form></Dialog>;
}
