import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { ConvexHttpClient } from "convex/browser";
import { makeFunctionReference } from "convex/server";

process.loadEnvFile("/tmp/origin-integration-qa.env");
const site = process.env.ORIGIN_PUBLIC_URL;
for (const url of [site, process.env.NEXT_PUBLIC_CONVEX_URL]) assert.equal(new URL(url).hostname, "127.0.0.1", "Synthetic tests only");
const { alex, sam, viewer, workspace } = JSON.parse(await readFile("/tmp/origin-qa-session.json", "utf8"));
const client = new ConvexHttpClient(process.env.NEXT_PUBLIC_CONVEX_URL, { logger: false });
const q = (name, args) => client.query(makeFunctionReference(name), args);
const request = (who, route, init = {}, conversation = "") => fetch(`${site}/api/local-chat/${route}${route.includes("?") ? "&" : "?"}teamId=${workspace._id}${conversation ? `&conversation=${encodeURIComponent(conversation)}` : ""}`, { ...init, headers: { Authorization: `Bearer ${who.sessionToken}`, ...(init.body instanceof FormData ? {} : { "Content-Type": "application/json" }) } });
const post = body => ({ method: "POST", body: JSON.stringify(body) });
const patch = body => ({ method: "PATCH", body: JSON.stringify(body) });
const open = await request(alex, "conversations", post({ recipientId: sam.user._id }));
assert.ok(open.ok, await open.clone().text());
const { conversationId } = await open.json();
const reverse = await request(sam, "conversations", post({ recipientId: alex.user._id }));
assert.equal((await reverse.json()).conversationId, conversationId, "One conversation per pair");
assert.equal((await request(viewer, "conversations", post({ recipientId: alex.user._id }))).ok, false, "Viewer cannot start DM");
const posted = await request(alex, "messages", post({ body: `Private regression ${Date.now()}` }), conversationId);
assert.ok(posted.ok, await posted.clone().text());
const { message } = await posted.json();
assert.ok((await (await request(sam, "messages", {}, conversationId)).json()).messages.some(item => item.id === message.id));
assert.equal((await (await request(alex, "messages")).json()).messages.some(item => item.id === message.id), false, "DM never appears in shared chat");
assert.equal((await request(viewer, "messages", {}, conversationId)).ok, false, "Third workspace member cannot read DM");
assert.equal((await request(viewer, `messages?focus=${message.id}`, {}, conversationId)).ok, false);
assert.equal((await request(alex, `messages?focus=${message.id}`)).ok, false, "Cannot deep-link DM through shared chat");
assert.equal((await request(sam, "messages", post({ body: "Cross-channel reply", replyTo: message.id }))).ok, false);
assert.equal((await request(alex, "messages", patch({ id: message.id, body: "Leaked edit" }))).ok, false);
assert.equal((await request(sam, "messages", patch({ id: message.id, body: "Not the author" }), conversationId)).ok, false);
assert.equal((await request(sam, "messages", patch({ id: message.id, reaction: "like" }), conversationId)).ok, true);
assert.equal((await request(alex, "messages", patch({ id: message.id, pinned: true }), conversationId)).ok, true);
let conversations = (await (await request(sam, "conversations")).json()).conversations;
assert.ok(conversations.find(item => item.id === conversationId).unread > 0);
assert.equal((await request(sam, "conversations", patch({ messageId: message.id }), conversationId)).ok, true);
conversations = (await (await request(sam, "conversations")).json()).conversations;
assert.equal(conversations.find(item => item.id === conversationId).unread, 0);
assert.equal((await (await request(viewer, "conversations")).json()).conversations.some(item => item.id === conversationId), false);
console.log("PASS DM pair identity, shared/DM isolation, third-member denial, deep links, replies, edits, reactions and unread state");
const form = new FormData(); form.set("file", new Blob(["Private attachment test"], { type: "text/plain" }), "private-qa.txt");
const upload = await request(alex, "files", { method: "POST", body: form }, conversationId);
assert.ok(upload.ok, await upload.clone().text());
const { file } = await upload.json();
assert.equal((await request(sam, `files?id=${file.id}`, {}, conversationId)).ok, true);
assert.equal((await request(viewer, `files?id=${file.id}`, {}, conversationId)).status, 404);
assert.equal((await request(alex, `files?id=${file.id}`)).status, 404, "Private file not accessible in shared scope");
assert.equal((await request(alex, "messages", post({ body: "", attachmentIds: [file.id] }))).ok, false, "Cannot attach a private file to shared chat");
assert.equal((await request(alex, "messages", post({ body: "", attachmentIds: [file.id] }), conversationId)).ok, true);
const outsider = await client.action(makeFunctionReference("auth:signup"), { name: "DM outsider", email: `dm-outsider-${Date.now()}@example.test`, password: `Only-local-DM-${Date.now()}`, workspaceName: "Outside" });
assert.equal((await request(alex, "conversations", post({ recipientId: outsider.user._id }))).ok, false, "Recipient must be a workspace member");
assert.equal((await request(outsider, "messages", {}, conversationId)).ok, false);
const notificationPage = await q("notifications:list", { sessionToken: sam.sessionToken, teamId: workspace._id, unreadOnly: false, paginationOpts: { cursor: null, numItems: 50 } });
assert.equal(notificationPage.page.some(item => item.messageId === message.id), false, "DM metadata stays in private local storage");
console.log("PASS private attachments, cross-channel upload restrictions, outsider denial and no DM metadata leakage");
